spring:
  application:
    name: llm_chatbot
  profiles:
    include: secret

crawler:
  base-url: http://localhost:8000

logging:
  level:
    root: INFO
    summer_project.llm_chatbot.service: DEBUG
    summer_project.llm_chatbot.util: DEBUG

#external:
 # ai:
  #  base-url: 
